version: "3.1"

services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rollcall
      POSTGRES_USER: rcdbuser
      POSTGRES_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
        - db_root_password
        - db_password
    ports:
      - '5432:5432'
    restart: on-failure

  app:
    build: ./app
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      DISCORD_TOKEN_FILE: /run/secrets/discord_token
    secrets:
        - db_password
        - discord_token
    depends_on:
      - db
    restart: on-failure

secrets:
  db_password:
    file: secrets/db_password.txt
  db_root_password:
    file: secrets/db_root_password.txt
  discord_token:
    file: secrets/discord_token.txt
